[
  {
    id: "1",
    title: "Soothing Ginger Tea",
    ingredients: ["Ginger", "Honey", "Lemon"],
    preparation: "Boil water with ginger, add lemon and honey to taste.",
    usage: "Drink warm to soothe a sore throat.",
    symptoms: ["Sore Throat", "Cold"],
  },
  {
    id: "2",
    title: "Aloe Vera for Burns",
    ingredients: ["Aloe Vera Gel"],
    preparation: "Apply aloe vera gel to the affected area.",
    usage: "Use for minor burns to soothe and heal the skin.",
    symptoms: ["Skin Burns", "Sunburn"],
  },
  {
    id: "3",
    title: "Turmeric Milk",
    ingredients: ["Turmeric", "Milk", "Honey"],
    preparation: "Warm the milk, mix in turmeric and honey.",
    usage: "Drink before bed for anti-inflammatory benefits.",
    symptoms: ["Inflammation", "Joint Pain"],
  },
  {
    id: "4",
    title: "Garlic for Cold",
    ingredients: ["Garlic"],
    preparation: "Chew on a clove of garlic.",
    usage: "Helps to alleviate cold symptoms.",
    symptoms: ["Cold", "Flu"],
  },
  {
    id: "5",
    title: "Cinnamon Honey Tea",
    ingredients: ["Cinnamon", "Honey", "Hot Water"],
    preparation: "Steep cinnamon in hot water, add honey to taste.",
    usage: "Drink to soothe a sore throat.",
    symptoms: ["Sore Throat", "Cough"],
  },
  {
    id: "6",
    title: "Peppermint Tea",
    ingredients: ["Peppermint Leaves", "Hot Water"],
    preparation: "Steep peppermint leaves in hot water.",
    usage: "Drink to relieve digestive discomfort.",
    symptoms: ["Indigestion", "Gas"],
  },
  {
    id: "7",
    title: "Chamomile Tea for Relaxation",
    ingredients: ["Chamomile Flowers", "Hot Water"],
    preparation: "Steep chamomile flowers in hot water for 5 minutes.",
    usage: "Drink before bed to improve sleep quality.",
    symptoms: ["Insomnia", "Stress"],
  },
  {
    id: "8",
    title: "Honey Lemon Cough Syrup",
    ingredients: ["Honey", "Lemon Juice"],
    preparation: "Mix honey and lemon juice.",
    usage: "Take a spoonful to relieve cough.",
    symptoms: ["Cough", "Throat Irritation"],
  },
  {
    id: "9",
    title: "Oatmeal Bath for Skin Irritation",
    ingredients: ["Colloidal Oatmeal", "Warm Bath Water"],
    preparation: "Add colloidal oatmeal to warm bath water.",
    usage: "Soak to soothe irritated skin.",
    symptoms: ["Skin Irritation", "Eczema"],
  },
  {
    id: "10",
    title: "Salt Water Gargle",
    ingredients: ["Salt", "Warm Water"],
    preparation: "Dissolve salt in warm water.",
    usage: "Gargle to relieve sore throat and reduce oral bacteria.",
    symptoms: ["Sore Throat", "Oral Infections"],
  },
  {
    id: "11",
    title: "Apple Cider Vinegar for Digestion",
    ingredients: ["Apple Cider Vinegar", "Water"],
    preparation: "Mix a tablespoon of apple cider vinegar with water.",
    usage: "Drink to aid digestion.",
    symptoms: ["Indigestion", "Bloating"],
  },
  {
    id: "12",
    title: "Baking Soda for Heartburn",
    ingredients: ["Baking Soda", "Water"],
    preparation: "Dissolve a teaspoon of baking soda in water.",
    usage: "Drink to neutralize stomach acid.",
    symptoms: ["Heartburn", "Acid Reflux"],
  },
  {
    id: "13",
    title: "Eucalyptus Steam Inhalation",
    ingredients: ["Eucalyptus Oil", "Hot Water"],
    preparation: "Add a few drops of eucalyptus oil to hot water.",
    usage: "Inhale the steam to clear nasal congestion.",
    symptoms: ["Nasal Congestion", "Sinusitis"],
  },
  {
    id: "14",
    title: "Banana for Energy Boost",
    ingredients: ["Banana"],
    preparation: "Eat a ripe banana.",
    usage: "Provides a quick energy boost with natural sugars and fiber.",
    symptoms: ["Fatigue", "Low Energy"],
  },
  {
    id: "15",
    title: "Coconut Oil for Dry Skin",
    ingredients: ["Coconut Oil"],
    preparation: "Apply coconut oil to dry skin areas.",
    usage: "Moisturizes and nourishes the skin.",
    symptoms: ["Dry Skin", "Flakiness"],
  },
  {
    id: "16",
    title: "Yogurt for Gut Health",
    ingredients: ["Yogurt"],
    preparation: "Consume a serving of plain yogurt.",
    usage: "Promotes a healthy digestive tract with probiotics.",
    symptoms: ["Digestive Issues", "Gut Imbalance"],
  },
  {
    id: "17",
    title: "Ginger for Nausea",
    ingredients: ["Ginger"],
    preparation: "Chew on a small piece of ginger or drink ginger tea.",
    usage: "Helps to alleviate nausea and digestive upset.",
    symptoms: ["Nausea", "Motion Sickness"],
  },
  {
    id: "18",
    title: "Tea Tree Oil for Acne",
    ingredients: ["Tea Tree Oil", "Carrier Oil"],
    preparation:
      "Dilute tea tree oil with a carrier oil and apply to affected areas.",
    usage: "Natural antimicrobial properties help reduce acne.",
    symptoms: ["Acne", "Skin Blemishes"],
  },
  {
    id: "19",
    title: "Cucumber Slices for Puffy Eyes",
    ingredients: ["Cucumber"],
    preparation: "Cut cucumber into slices and chill.",
    usage: "Place over eyes to reduce puffiness and refresh tired eyes.",
    symptoms: ["Puffy Eyes", "Eye Fatigue"],
  },
  {
    id: "20",
    title: "Honey for Minor Cuts",
    ingredients: ["Honey"],
    preparation: "Apply a small amount of honey to minor cuts or grazes.",
    usage: "Natural antibacterial properties aid in healing.",
    symptoms: ["Minor Cuts", "Grazes"],
  },
  {
    id: "21",
    title: "Lavender Essential Oil Sleep Aid",
    ingredients: ["Lavender Essential Oil", "Diffuser"],
    preparation:
      "Add a few drops of lavender essential oil to a diffuser before bedtime.",
    usage: "Inhale the aroma to promote relaxation and improve sleep quality.",
    symptoms: ["Insomnia", "Stress", "Anxiety"],
  },
  {
    id: "22",
    title: "Golden Honey Immunity Booster",
    ingredients: ["Raw Honey", "Turmeric Powder", "Black Pepper"],
    preparation: "Mix turmeric and a pinch of black pepper into raw honey.",
    usage: "Consume a spoonful daily to boost immunity and fight inflammation.",
    symptoms: ["Low Immunity", "Inflammation", "Seasonal Allergies"],
  },
  {
    id: "23",
    title: "Activated Charcoal for Detox",
    ingredients: ["Activated Charcoal Powder", "Water", "Lemon Juice"],
    preparation:
      "Stir activated charcoal powder into water and add a splash of lemon juice.",
    usage: "Drink to absorb toxins and cleanse the digestive system.",
    symptoms: ["Bloating", "Toxin Buildup", "Digestive Issues"],
  },
  {
    id: "24",
    title: "Rosehip Oil for Skin Regeneration",
    ingredients: ["Rosehip Oil"],
    preparation:
      "Apply rosehip oil directly to the face or affected skin areas.",
    usage: "Use to hydrate skin, reduce scars, and promote regeneration.",
    symptoms: ["Dry Skin", "Acne Scars", "Wrinkles"],
  },
  {
    id: "25",
    title: "Matcha Green Tea Energy Shot",
    ingredients: ["Matcha Green Tea Powder", "Hot Water", "Honey (optional)"],
    preparation:
      "Whisk matcha powder in hot water until frothy and add honey if desired.",
    usage:
      "Drink in the morning or before exercise for a natural energy boost.",
    symptoms: ["Fatigue", "Low Energy", "Mental Fog"],
  },
  {
    id: "26",
    title: "Thyme Steam for Respiratory Relief",
    ingredients: ["Thyme", "Hot Water"],
    preparation: "Add thyme to boiling water and inhale the steam.",
    usage: "Use to clear respiratory passages and ease breathing.",
    symptoms: ["Bronchitis", "Sinus Congestion", "Respiratory Infections"],
  },
  {
    id: "27",
    title: "Arnica Salve for Bruises and Swelling",
    ingredients: ["Arnica Flowers", "Coconut Oil", "Beeswax"],
    preparation:
      "Infuse arnica flowers in coconut oil, strain, and mix with melted beeswax to form a salve.",
    usage:
      "Apply to bruises and swollen areas to reduce inflammation and speed healing.",
    symptoms: ["Bruises", "Swelling", "Muscle Soreness"],
  },
  {
    id: "28",
    title: "Flaxseed Gel for Digestive Health",
    ingredients: ["Flaxseeds", "Water"],
    preparation: "Soak flaxseeds in water overnight, strain, and use the gel.",
    usage:
      "Consume the gel or add to smoothies to improve digestion and bowel movements.",
    symptoms: [
      "Constipation",
      "Irritable Bowel Syndrome",
      "Digestive Discomfort",
    ],
  },
  {
    id: "29",
    title: "Himalayan Salt Sole for Hydration",
    ingredients: ["Himalayan Pink Salt", "Water"],
    preparation:
      "Dissolve Himalayan salt in water to create a sole (salt solution).",
    usage:
      "Drink a teaspoon of the sole mixed in a glass of water each morning on an empty stomach.",
    symptoms: ["Dehydration", "Electrolyte Imbalance", "Detoxification"],
  },
  {
    id: "30",
    title: "Mint and Lemon Foot Soak",
    ingredients: ["Mint Leaves", "Lemon", "Warm Water", "Epsom Salt"],
    preparation:
      "Combine mint leaves, lemon slices, and Epsom salt in warm water.",
    usage: "Soak feet to refresh and relieve tired, achy feet.",
    symptoms: ["Foot Odor", "Swollen Feet", "Tired Feet"],
  },
];
