symptoms = [
  "Sore Throat",
  "Cold",
  "Skin Burns",
  "Sunburn",
  "Inflammation",
  "Joint Pain",
  "Flu",
  "Cough",
  "Indigestion",
  "Gas",
  "Insomnia",
  "Stress",
  "Throat Irritation",
  "Skin Irritation",
  "Eczema",
  "Oral Infections",
  "Bloating",
  "Heartburn",
  "Acid Reflux",
  "Nasal Congestion",
  "Sinusitis",
  "Fatigue",
  "Low Energy",
  "Dry Skin",
  "Flakiness",
  "Digestive Issues",
  "Gut Imbalance",
  "Nausea",
  "Motion Sickness",
  "Acne",
  "Skin Blemishes",
  "Puffy Eyes",
  "Eye Fatigue",
  "Minor Cuts",
  "Grazes",
  "Dehydration",
  "Electrolyte Imbalance",
  "Detoxification",
  "Foot Odor",
  "Swollen Feet",
  "Tired Feet",
  "Bronchitis",
  "Respiratory Infections",
  "Muscle Soreness",
  "Constipation",
  "Irritable Bowel Syndrome",
  "Digestive Discomfort",
];
